toolssite/urls.py
"""
Tools site URL Configuration
"""

from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.utils.translation import gettext_lazy as _

from tool.sitemaps import StaticViewSitemap
from tool.views.views import (
    CalendarView,
    CanvasesView,
    CanvasView,
    CodeView,
    DictionaryView,
    FakeCheckView,
    FlashcardsView,
    LinkView,
    ProfileView,
    TasksView,
    TracerouteView,
    about_page,
    card_order,
    link_order,
    log_in,
    log_out,
    task_order,
    tool,
    user_events,
    users_list,
    ShoppingListsView,
    ShoppingListView,
)

sitemaps = {
    "static": StaticViewSitemap,
}


urlpatterns = [
    path("", tool, name="main", kwargs={"slug": "text-manipulation"}),
    path("ajax", tool, name="ajax_main", kwargs={"slug": "text-manipulation"}),
    path("tool/<str:slug>", tool, name="tool"),
    path("ajax/tool/<str:slug>", tool, name="ajax_tool"),
    path("user/<str:username>/tool/<str:slug>", tool, name="user_tool"),
    path("ajax/user/<str:username>/tool/<str:slug>", tool, name="ajax_user_tool"),
    path("calendar", CalendarView.as_view(), name="calendar"),
    path("ajax/calendar", CalendarView.as_view(), name="ajax_calendar"),
    path("user/<str:username>/calendar", CalendarView.as_view(), name="user_calendar"),
    path(
        "ajax/user/<str:username>/calendar",
        CalendarView.as_view(),
        name="ajax_user_calendar",
    ),
    path("calendar/<int:pk>", CalendarView.as_view(), name="calendar_pk"),
    path("ajax/calendar/<int:pk>", CalendarView.as_view(), name="ajax_calendar_pk"),
    path(
        "user/<str:username>/calendar/<int:pk>",
        CalendarView.as_view(),
        name="user_calendar_pk",
    ),
    path(
        "ajax/user/<str:username>/calendar/<int:pk>",
        CalendarView.as_view(),
        name="ajax_user_calendar_pk",
    ),
    path("dictionary", DictionaryView.as_view(), name="dictionary"),
    path("ajax/dictionary", DictionaryView.as_view(), name="ajax_dictionary"),
    path(
        "user/<str:username>/dictionary",
        DictionaryView.as_view(),
        name="user_dictionary",
    ),
    path(
        "ajax/user/<str:username>/dictionary",
        DictionaryView.as_view(),
        name="ajax_user_dictionary",
    ),
    path("flashcards", FlashcardsView.as_view(), name="flashcards"),
    path("ajax/flashcards", FlashcardsView.as_view(), name="ajax_flashcards"),
    path(
        "user/<str:username>/flashcards",
        FlashcardsView.as_view(),
        name="user_flashcards",
    ),
    path(
        "ajax/user/<str:username>/flashcards",
        FlashcardsView.as_view(),
        name="ajax_user_flashcards",
    ),
    path("flashcards/<int:pk>", FlashcardsView.as_view(), name="flashcards_pk"),
    path(
        "ajax/flashcards/<int:pk>", FlashcardsView.as_view(), name="ajax_flashcards_pk"
    ),
    path("tasks", TasksView.as_view(), name="tasks"),
    path("ajax/tasks", TasksView.as_view(), name="ajax_tasks"),
    path("user/<str:username>/tasks", TasksView.as_view(), name="user_tasks"),
    path("ajax/user/<str:username>/tasks", TasksView.as_view(), name="ajax_user_tasks"),
    path("tasks/<int:pk>", TasksView.as_view(), name="tasks_pk"),
    path("ajax/tasks/<int:pk>", TasksView.as_view(), name="ajax_tasks_pk"),
    path("user/<str:username>/canvases", CanvasesView.as_view(), name="canvases"),
    path("canvas/<str:slug>", CanvasView.as_view(), name="canvas"),
    path("code", CodeView.as_view(), name="code"),
    path("ajax/code", CodeView.as_view(), name="ajax_code"),
    path("traceroute", TracerouteView.as_view(), name="traceroute"),
    path("ajax/traceroute", TracerouteView.as_view(), name="ajax_traceroute"),
    path("news-check", FakeCheckView.as_view(), name="news_check"),
    path("ajax/news-check", FakeCheckView.as_view(), name="ajax_news_check"),
    path("user/<str:username>/code", CodeView.as_view(), name="user_code"),
    path("ajax/user/<str:username>/code", CodeView.as_view(), name="ajax_user_code"),
    path("code/<str:slug>", CodeView.as_view(), name="code_slug"),
    path("ajax/code/<str:slug>", CodeView.as_view(), name="ajax_code_slug"),
    path("shopping_lists", ShoppingListsView.as_view(), name="shopping_lists"),
    path("shopping_lists/<int:pk>", ShoppingListView.as_view(), name="shopping_list"),
    path(
        "ajax/shopping_lists", ShoppingListsView.as_view(), name="ajax_shopping_lists"
    ),
    path(
        "ajax/shopping_lists/<int:pk>",
        ShoppingListView.as_view(),
        name="ajax_shopping_list",
    ),
    path("links", LinkView.as_view(), name="links"),
    path("ajax/links", LinkView.as_view(), name="ajax_links"),
    path("links/<int:pk>", LinkView.as_view(), name="links_pk"),
    path("ajax/links/<int:pk>", LinkView.as_view(), name="ajax_links_pk"),
    path("user/<str:username>/links", LinkView.as_view(), name="user_links"),
    path("ajax/user/<str:username>/links", LinkView.as_view(), name="ajax_user_links"),
    path("users", users_list, name="users"),
    path("ajax/users", users_list, name="ajax_users"),
    path("user/<str:username>", ProfileView.as_view(), name="user"),
    path("ajax/user/<str:username>", ProfileView.as_view(), name="ajax_user"),
    path("events", user_events, name="events"),
    path("user/<str:username>/card-order", card_order, name="card_order"),
    path("user/<str:username>/task-order", task_order, name="task_order"),
    path("user/<str:username>/link-order", link_order, name="link_order"),
    path("about", about_page, name="about_page"),
    path("ajax/about", about_page, name="ajax_about_page"),
    path("login", log_in, name="login"),
    path("ajax/login", log_in, name="ajax_login"),
    path("logout", log_out, name="logout"),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("schedule/", include("schedule.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("admin/", admin.site.urls),
]
admin.site.site_header = _("Tools administration")

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

tool/models.py
import random
import string
import textwrap
from collections import namedtuple
from datetime import datetime, date

import pytz
import requests
from bs4 import BeautifulSoup
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.core.validators import MaxValueValidator, MinValueValidator, URLValidator
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.utils.translation import gettext as _
from phonenumber_field.modelfields import PhoneNumberField

from tool.widgets import ColorWidget

User = get_user_model()

TIMEZONES = sorted(
    [
        (tz, tz + " " + datetime.now(pytz.timezone(tz)).strftime("%z"))
        for tz in pytz.common_timezones
    ]
)

default_palette_colors = (
    "f5f5f5",
    "dff0d8",
    "d9edf7",
    "fcf8e3",
    "f2dede",
)

_char_map = string.ascii_letters + string.digits


def number_to_chars(num: int) -> str:
    base = len(_char_map)
    if num == 0:
        return _char_map[0]
    digits = []
    while num:
        digits.append(_char_map[int(num % base)])
        num //= base
    return "".join(map(str, digits[::-1]))


def save_and_add_slug(
    obj, force_insert=False, force_update=False, using=None, update_fields=None
):
    need_slug = not obj.pk
    super(type(obj), obj).save(
        force_insert=force_insert,
        force_update=force_update,
        using=using,
        update_fields=update_fields,
    )
    if need_slug:
        obj.slug = "".join(random.sample(_char_map, 3)) + number_to_chars(obj.pk)
        obj.save()


def get_username_by_uid(obj):
    """Helper function to get user username by user id."""
    # Try to get username from the cache to avoid unneeded queries,
    # pattern is 'username_by_id_<user_id>'
    username = cache.get(f"username_by_id_{obj.user_id}")
    if not username:
        # We don't have the username - get username and set it to the cache.
        username = obj.user.username
        cache.set(
            f"username_by_id_{obj.user_id}",
            username,
            settings.USER_ONLINE_TIMEOUT,
        )

    return username


class ColorField(models.CharField):
    """Color field."""

    def formfield(self, **kwargs):
        kwargs["widget"] = ColorWidget
        return super().formfield(**kwargs)


class Profile(models.Model):
    """Profile model."""

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name="profile", on_delete=models.CASCADE
    )
    timezone = models.CharField(max_length=64, blank=True, null=True)
    avatar = models.ImageField(
        upload_to="avatars/", default="/media/avatars/no-avatar.png"
    )
    phone_number = PhoneNumberField(blank=True)

    def __str__(self):
        return get_username_by_uid(self)


for i, default_color in enumerate(default_palette_colors, 1):
    Profile.add_to_class(
        "palette_color_" + str(i), ColorField(max_length=6, default=default_color)
    )


class Card(models.Model):
    """Flashcard model."""

    DIFFICULTIES = (
        ("easy", "Easy"),
        ("middle", "Medium"),
        ("difficult", "Difficult"),
    )

    word = models.CharField(max_length=60)
    description = models.TextField(blank=True, null=True)
    difficulty = models.CharField(
        max_length=10, choices=DIFFICULTIES, default="difficult"
    )
    user = models.ForeignKey(User, related_name="cards", on_delete=models.CASCADE)
    order = models.PositiveSmallIntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)
    changed_date = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (("word", "user"),)

    def __str__(self):
        return self.word


class Word(models.Model):
    """Word model."""

    user = models.ForeignKey(User, related_name="words", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return getattr(self, "en", "-")


for lang in settings.LANGUAGES:
    Word.add_to_class(lang[0], models.CharField(max_length=60, null=True, blank=True))


class Label(models.Model):
    """Label model."""

    CATEGORIES = (
        ("programing", "Programing"),
        ("links", "Links"),
    )

    title = models.CharField(max_length=60)
    user = models.ForeignKey(
        User, related_name="labels", on_delete=models.CASCADE, null=True, blank=True
    )
    category = models.CharField(max_length=16, choices=CATEGORIES, default="programing")
    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Task(models.Model):
    """Task model."""

    STATUSES = (
        ("todo", "TODO"),
        ("doing", "Doing"),
        ("done", "Done"),
    )
    RESOLUTIONS = (
        ("fixed", "Fixed"),
        ("won't fix", "Won't Fix"),
        ("duplicate", "Duplicate"),
        ("incomplete", "Incomplete"),
        ("Cannot Reproduce", "Cannot Reproduce"),
        ("obsolete", "Obsolete"),
        ("works as designed", "Works as Designed"),
        ("done", "Done"),
        ("won't Do", "Won't Do"),
    )

    title = models.CharField(max_length=60)
    description = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUSES, default="todo")
    resolution = models.CharField(
        max_length=20, choices=RESOLUTIONS, blank=True, null=True
    )
    progress = models.PositiveSmallIntegerField(
        default=0, blank=True, validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    labels = models.ManyToManyField(Label, blank=True)
    color = models.PositiveSmallIntegerField(
        default=1,
        validators=[
            MinValueValidator(1),
            MaxValueValidator(len(default_palette_colors)),
        ],
    )
    user = models.ForeignKey(User, related_name="tasks", on_delete=models.CASCADE)
    weight = models.SmallIntegerField(default=0)
    due_date = models.DateTimeField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    changed_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Canvas(models.Model):
    """Canvas model."""

    user = models.ForeignKey(User, related_name="canvases", on_delete=models.CASCADE)
    canvas = models.TextField(blank=True, null=True)
    slug = models.CharField(max_length=10, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        save_and_add_slug(self, force_insert, force_update, using, update_fields)

    def preview(self):
        return format_html('<img src="{}" />', self.canvas)

    preview.short_description = "Image"
    preview.allow_tags = True

    def __str__(self):
        return f"{get_username_by_uid(self)}: {self.pk}"


class Code(models.Model):
    """Code model."""

    title = models.CharField(max_length=60)
    text = models.TextField(help_text=_("Double click on code block to copy or edit."))
    user = models.ForeignKey(
        User, related_name="code_fragments", on_delete=models.CASCADE
    )
    slug = models.CharField(max_length=10, unique=True)
    labels = models.ManyToManyField(
        Label,
        blank=True,
        help_text=_(
            "Used programming languages will be automatically" " saved as labels."
        ),
    )
    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (("title", "user"),)

    def link_to_code_snippet(self):
        return (
            format_html(
                '<a href="{}">{}</a>',
                reverse("code_slug", kwargs={"slug": self.slug}),
                self.title,
            )
            if self.slug
            else ""
        )

    @classmethod
    def get_code_snippets_with_labels(cls, user, label=None):
        """Get code snippets with labels."""
        code_snippets = cls.objects.filter(user=user)
        if label:
            code_snippets = code_snippets.filter(labels__title=label)
        code_snippets = code_snippets.order_by("-pk").values_list(
            "title", "slug", "labels__title", named=True
        )

        code_snippets_dict = {}
        for snippet in code_snippets:
            snippet = snippet._asdict()
            snippet["labels__title"] = [snippet["labels__title"]]
            if snippet["labels__title"][0] is None:
                snippet["labels__title"] = []

            if snippet["slug"] in code_snippets_dict:
                code_snippets_dict[snippet["slug"]]["labels__title"] += snippet[
                    "labels__title"
                ]
            else:
                code_snippets_dict[snippet["slug"]] = snippet

        for slug, snippet in code_snippets_dict.items():
            code_snippets_dict[slug] = namedtuple("Row", snippet.keys())(**snippet)

        return code_snippets_dict.values()

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        save_and_add_slug(self, force_insert, force_update, using, update_fields)

    def __str__(self):
        return f"{get_username_by_uid(self)}: {self.title}"


class Link(models.Model):
    """Link model."""

    link = models.CharField(
        max_length=128, validators=[URLValidator(["http", "https"])]
    )
    title = models.CharField(max_length=64, blank=True, null=True)
    description = models.CharField(max_length=128, blank=True, null=True)
    color = ColorField(max_length=6, default="000000")
    weight = models.SmallIntegerField(default=0)
    category = models.ForeignKey(
        Label, related_name="links", on_delete=models.SET_NULL, blank=True, null=True
    )

templates/calendar.html
{% extends parent_template %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{% trans "Calendar" %}{% endblock %}
{% block description %}{% trans "Add events to your Calendar and get email notifications about upcoming events" %}{% endblock description %}

{% block content %}
    <!-- Button trigger modal -->
    <button type="button" class="add-btn btn btn-default btn-md" data-toggle="modal" data-target="#add-item" data-annyang="add event">
      <span class="glyphicon glyphicon-plus"></span> {% trans "Add event" %}
    </button>

    <!-- Modal -->
    {% include "modal-form.html" %}

    <div id="calendar"></div>
    <script>
        if("undefined" === typeof jQuery) {
            window.onload = function() {
                init_app();
            };
        }
        else {
            init_app();
        }
        function init_app() {
            var $end_recurring_period;
            var $modal;
            var result;
            var pk;

            // Dynamically set page title and description.
            document.title = '{% trans "Calendar" %}';
            document.head.querySelector('meta[name=description]').content = '{% trans "Add events to your Calendar and get email notifications about upcoming events" %}';

            $modal = $('#content').find('.modal');
            $end_recurring_period = $modal.find('#id_end_recurring_period').closest('.form-group');
            $end_recurring_period.hide();

            $('#calendar').fullCalendar({
                events: '/schedule/api/occurrences?calendar_slug={{ profile_user.username }}&timezone={{ profile.timezone }}',
                ignoreTimezone: false,
                timeFormat: 'H:mm',
                eventClick: function(calEvent, jsEvent, view) {
                    // Show modal, remove errors and set hidden id field.
                    $modal.modal();
                    $modal.find('.alert').remove();
                    $modal.find('#id_id').val(calEvent.event_id);
                    $modal.find('.btn.delete').show();
                    if (calEvent.rule) {
                        $end_recurring_period.show();
                    }

                    $modal.find('#id_title').val(calEvent.title);
                    $modal.find('#id_description').val(calEvent.description);
                    $modal.find('#id_start').val(moment(calEvent.start._i).format('YYYY-MM-DD HH:mm'));
                    $modal.find('#id_end').val(moment(calEvent.end._i).format('YYYY-MM-DD HH:mm'));
                    $modal.find('#id_color_event').val(calEvent.color.slice(1));
                    $modal.find('#id_color_event')[0].jscolor.importColor(calEvent.color.slice(1));
                    $modal.find('#id_rule option').each(function() {
                        if ($(this).text().indexOf(calEvent.rule) !== -1) {
                            $modal.find('#id_rule').val($(this).text()).change();
                            $(this).attr("selected", "selected").prop("selected", "selected");
                        }
                    });

                },
                dayClick: function(date, jsEvent, view) {
                    $('#add-event').modal('show');
                },
                eventAfterRender: function(event, element) {
                    $(element).tooltip({
                        title:event.description,
                        container: "body"
                    });
                }
            });

            $('form .btn.delete').click(function() {
                result = confirm('{% trans "Are you sure you want to delete this event?" %}');
                if (result) {
                    pk = $(this).closest('form').find('#id_id').val();
                    $.ajax({
                        url: "{% url 'user_calendar' profile_user.username %}" + '/' + pk,
                        type: 'DELETE',
                        beforeSend: function(xhr) {
                            xhr.setRequestHeader('X-CSRFTOKEN', '{{ csrf_token }}');
                        },
                        success: function(result) {
                            window.location.replace(result.redirect);
                        }
                    });
                }
                return false;
            });

            // Hide end of recurring period field.
            $(document).on('hidden.bs.modal', '.modal', function() {
                $end_recurring_period.hide();
            });

            $modal.find("#id_rule").change(function() {
                if ($(this).val()) {
                    $end_recurring_period.show();
                }
                else {
                    $end_recurring_period.hide();
                }
            });
        }
    </script>
{% endblock content %}

templates/code.html
{% extends parent_template %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{{ page_title }}{% endblock %}
{% block description %}{% trans "Instantly share code, notes, and snippets" %}{% endblock description %}

{% block content %}
    <style>
        .cke_bottom {
            display: none !important;
        }
        form .btn-danger {
          margin-right: 15px;
        }
        .select2-container {
            display: block;
        }
    </style>

    <h2>{% trans "Code snippets" %}</h2>

    {% if codes %}
        <table id="codes" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>{% trans "Title" %}</th>
                    <th>{% trans "Labels" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for code in codes %}
                    <tr>
                        <td><a href="{% url 'code_slug' code.slug %}" class="ajax-link">{{ code.title }}</a></td>
                        <td>
                            {% for label in code.labels__title %}
                                <a class="ajax-link" href="{% url 'code' %}?label={{ label }}">{{ label }}</a>{% if not forloop.last %},{% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <h3>{% trans "Add Code snippet" %}</h3>
    {% endif %}

    <form method="post" class="add-form clearfix form-horizontal">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label class="col-sm-12" for="{{ field.auto_id }}">{{ field.label_tag }}</label>
                <div class="col-sm-12">
                    {% if field.name == 'text' %}
                        {{ field|add_class:"ckeditor" }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                    <small class="text-muted">{{ field.help_text }}</small>
                </div>
                {% if field.errors %}
                    <div class="col-sm-12" role="alert">
                        <div class="alert alert-warning" >
                            {{ field.errors }}
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        {% if save_btn %}
            <button type="submit" class="btn btn-primary btn-md pull-right">{% trans "Save" %}</button>
        {% endif %}
        {% if delete_btn %}
            <button type="submit" class="btn btn-danger btn-md pull-right">{% trans "Delete" %}</button>
        {% endif %}
    </form>


    <script>
        // Dynamically set page title and description.
        document.title = '{{ page_title }}';
        document.head.querySelector('meta[name=description]').content = '{% trans "Instantly share code, notes, and snippets" %}';

        if("undefined" === typeof jQuery) {
            window.onload = function() {
                init_app();
            };
        }
        else {
            init_app();
        }
        function init_app() {
            $('#id_labels').select2({
                dropdownAutoWidth : true,
                width: 'auto'
            });
        }
    </script>
    <script src="{% static 'bower_components/ckeditor/ckeditor.js' %}"></script>
    <script src="{% static 'js/code.js' %}" defer></script>

{% endblock %}

templates/dummy_parent.html
{% block content %}{% endblock %}

templates/fake_check.html
{% extends parent_template %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block title %}{{ page_title }}{% endblock %}
{% block description %}{% trans "Check if news are real or fake" %}{% endblock description %}

{% block content %}
    <h2>{% trans "Check if news are real or fake" %}</h2>

    <form method="post" class="clearfix">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label" for="title">{% trans "Title" %}</label>
            <input id="title" type="text" class="form-control" required value="{{ title }}" name="title">
        </div>
        <div class="form-group">
            <label class="control-label" for="text">{% trans "Text" %}</label>
            <textarea rows="12" class="col-xs-12" id="text" name="text" required>{{ text }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary btn-md pull-right mt-3">{% trans "Check" %}</button>
    </form>

    {% if probability %}
        <h3>{% trans "Results" %}:</h3>
        <h4><u>{{ label|capfirst }}</u> - {{ probability }}% probability</h4>
    {% endif %}

{% endblock %}

templates/links.html
{% extends parent_template %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}

{% block title %}{% trans "Read it later" %}{% endblock %}
{% block description %}{% trans "Save links to read it later" %}{% endblock description %}

{% block content %}
    {% include "modal-form.html" %}

    <div class="container-fluid no-padding row cards-filters">
      <div class="col-md-4">
        <!-- Button trigger modal -->
        <button type="button" class="add-btn btn btn-default btn-md" data-toggle="modal" data-target="#add-item" data-annyang="add link">
          <span class="glyphicon glyphicon-plus"></span> {% trans "Add a link" %}
        </button>
      </div>
      <div class="col-md-4 col-sm-6">
        <ul class="difficulty-filters">
            {% for color in palette %}
                <li><a href="#" class="difficulty-filter color-filter active" style="background-color: #{{ color }};" data-difficulty="{{ color }}"></a></li>
            {% endfor %}
        </ul>
      </div>
      <div class="col-md-4 col-sm-6">
        <div class="input-group pull-right">
          <input id="card-search" type="text" class="form-control" placeholder="Search">
        </div>
      </div>
    </div>

    <ul id="links" class="cards sortable list-group">
      {% for category, links in categorized_links %}
        {% trans "No category" as no_category %}
        <div class="links list-group-item"><h4>{{ category|default:no_category }}</h4>
          {% for link in links %}
            <li class="link-container item-container" data-difficulty="{{ link.color }}" data-title="{{ link.link }}" data-id="{{ link.id }}" data-json="{{ link|serialize }}">
              <small class="glyphicon glyphicon-move" aria-hidden="true"></small>
              <a target="_blank" rel="noopener nofollow" href="{{ link.link }}" class="link" style="font-size: 1.2em; color: #{{ link.color }};" data-toggle="tooltip" data-html="true" title="{% if link.title != None %}<b>{{ link.title }}</b>{% endif %}{% if link.description != None %}<p>{{ link.description }}</p>{% endif %}">
                {{ link.link }}
              </a>
              <a href="/admin/tool/link/{{ link.id }}/change/" class="edit">
                <small class="glyphicon glyphicon-pencil" aria-hidden="true"></small>
              </a>
            </li>
          {% endfor %}
        </div>
      {% endfor %}
    </ul>

    <script defer>
      if("undefined" === typeof jQuery) {
        window.onload = function() {
          init_app();
        };
      }
      else {
        init_app();
      }

      function init_app() {
        let $cards_container = $('.links');
        let $this;
        let $difficulty_filters = $('.difficulty-filter');
        let $card_search = $('#card-search');
        let substring;
        let order;
        let result;
        let pk;

        // Dynamically set page title and description.
        document.title = '{% trans "Read it later" %}';
        document.head.querySelector('meta[name=description]').content = '{% trans "Save links to read it later" %}';

        $('.item-container .link').tooltip();

        $('select#id_color').select2({
          minimumResultsForSearch: -1,
          escapeMarkup: function(markup) {
            return '<div style="padding: 0 5px 0 10px; line-height: 26px; color: #' + markup + '; background-color: #' + markup + ';">' + markup + '</div>';
          }
        });
        $('select#id_resolution').select2({width: '150px'});

        $difficulty_filters.click(function() {
          $this = $(this);
          $this.toggleClass('active');
          $cards_container.find('.link-container[data-difficulty=' + $this.data('difficulty') + ']').toggle($this.hasClass('active')).toggleClass('difficulty-hidden');

          return false;
        });

        $card_search.on('input', function(_) {
          substring = this.value;

          $cards_container.find('.link-container:not(.difficulty-hidden)').each(function(_) {
            $this = $(this);
            if ($this.data('title') === substring || $this.data('title').toString().indexOf(substring) !== -1) {
              $this.show();
            }
            else {
              $this.hide();
            }
          });
        });

        $('form .btn.delete').click(function() {
          result = confirm('{% trans "Are you sure you want to delete this link?" %}');
          if (result) {
            pk = $(this).closest('form').find('#id_id').val();
            $.ajax({
              url: "{% url 'links' %}" + '/' + pk,
              type: 'DELETE',
              beforeSend: function(xhr) {
                xhr.setRequestHeader('X-CSRFTOKEN', '{{ csrf_token }}');
              },
              success: function(result) {
                window.location.replace(result.redirect);
              }
            });
          }
          return false;
        });

        $cards_container.sortable().on('sortupdate', function(_, __) {
          if (!$cards_container.hasClass('disabled')) {
            order = {};
            $cards_container.find('.item-container').each(function(index) {
              order[$(this).data('id')] = index;
            });
            $.post("{% url 'link_order' profile_user.username %}", {
              order: JSON.stringify(order),
              'csrfmiddlewaretoken': '{{ csrf_token }}'
            }, function() {
              $cards_container.addClass('disabled');
            })
            .always(function() {
              $cards_container.removeClass('disabled');
            });
          }
        });

      }
    </script>
{% endblock %}